### ISSUE TITLE
 raise NotImplementedError, NotImplementedError

### ISSUE THREAD

**Issue by VinACE** [mdv3101/CDeCNet#13]
$ python demo/image_demo.py border_less2.jpg configs/dcn/db_cascade_mask_rcnn_x101_fpn_dconv_c3-c5_1x_coco.py /home/devteam/CDeCNet/model/epoch_50.pth    --device 'cpu' --score-thr 0.95 --output-img 'output_demo.jpg'
which: no nvcc in (/home/devteam/.conda/envs/py38/bin:/opt/miniconda3/condabin:/home/devteam/.local/bin:/home/devteam/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/miniconda3/bin)
> /home/devteam/CDeCNet/mmdet/apis/inference.py(37)init_detector()

-> if checkpoint is not None:
(Pdb) c
> /home/devteam/CDeCNet/mmdet/apis/inference.py(91)inference_detector()
-> if next(model.parameters()).is_cuda:
(Pdb) c
/home/devteam/CDeCNet/mmdet/apis/inference.py:91: UserWarning: We set use_torchvision=True in CPU mode.
  if next(model.parameters()).is_cuda:
Traceback (most recent call last):
  File "demo/image_demo.py", line 28, in <module>
    main()
  File "demo/image_demo.py", line 22, in main
    result = inference_detector(model, args.img)
  File "/home/devteam/CDeCNet/mmdet/apis/inference.py", line 91, in inference_detector
    if next(model.parameters()).is_cuda:
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/core/fp16/decorators.py", line 51, in new_func
    return old_func(*args, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/models/detectors/base.py", line 148, in forward
    return self.forward_test(img, img_metas, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/models/detectors/base.py", line 129, in forward_test
    return self.simple_test(imgs[0], img_metas[0], **kwargs)
  File "/home/devteam/CDeCNet/mmdet/models/detectors/two_stage.py", line 184, in simple_test
    x = self.extract_feat(img)
  File "/home/devteam/CDeCNet/mmdet/models/detectors/two_stage.py", line 76, in extract_feat
    x = self.backbone(img)
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/models/backbones/db_resnet.py", line 714, in forward
    second_x = second_res_layer(second_x)
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/models/backbones/db_resnet.py", line 280, in forward
    out = _inner_forward(x)
  File "/home/devteam/CDeCNet/mmdet/models/backbones/db_resnet.py", line 257, in _inner_forward
    out = self.conv2(out)
  File "/home/devteam/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/devteam/CDeCNet/mmdet/ops/dcn/deform_conv.py", line 295, in forward
    return deform_conv(x, offset, self.weight, self.stride, self.padding,
  File "/home/devteam/CDeCNet/mmdet/ops/dcn/deform_conv.py", line 47, in forward
    raise NotImplementedError
NotImplementedError

**Comment by madhav1ag** [comment]
Hi,
Can you please be more descriptive about the error you are facing?

**Comment by VinACE** [comment]
I was getting the following error for some reason, I am not sure if that is because  I was using only CPU version while running the demo script, python demo/image_demo.py
File "/home/devteam/CDeCNet/mmdet/ops/dcn/deform_conv.py", line 47, in forward
raise NotImplementedError
NotImplementedError

**Comment by madhav1ag** [comment]
Deform_conv layers are implemented in CUDA only. Please refer #10
