### ISSUE TITLE
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

### ISSUE THREAD

**Issue by arnyao** [mdv3101/CDeCNet#18]
hello~
When I ran the program, I found this error. Do you know how to solve it,

Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/apis/train.py", line 179, in train_detector
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 125, inrun
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/epoch_based_runner.py", line 47, in train
    for i, data_batch in enumerate(self.data_loader):
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in_worker_loop
    data = fetcher.fetch(index)
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jsj201-2/.conda/envs/open-mmlab/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/custom.py", line 144, in __getitem__
    data = self.prepare_train_img(idx)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/custom.py", line 157, in prepare_train_img
    return self.pipeline(results)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/compose.py", line 25, in __call__
    data = t(data)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/transforms.py", line 306, in __call__
    self._pad_masks(results)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/datasets/pipelines/transforms.py", line 298, in _pad_masks
    pad_shape[:2], pad_val=self.pad_val)
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/core/mask/structures.py", line 179, in pad
    for mask in self.masks
  File "/home/jsj201-2/mount1/lxy/CDeCNet/mmdet/core/mask/structures.py", line 179, in <listcomp>
    for mask in self.masks
TypeError: impad() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given

I hope you can help me solve this problem. Thank you very much

**Comment by letuantang** [comment]
@arnyao I got the same problem. Can you share with me how to solve it. Thank you very much.

**Comment by selimceylan** [comment]
Hi @letuantang, I was struggling same problem but for another class. I solved this with downgrading my mmdet version to 2.11. You can try lower versions.
I hope it will helps who encounter this issue.
