### ISSUE TITLE
Error in open-mmlab://resnext101_32x4d

### ISSUE THREAD

**Issue by srgautam9** [mdv3101/CDeCNet#24]
After changing all the codes as per my system/cuda I tried running.
But I am facing the below error, could you please help me.

**2023-02-07 16:12:29,370 - root - INFO - load model from: open-mmlab://resnext101_32x4d**
Traceback (most recent call last):
File "tools/train.py", line 161, in <module>
main()
File "tools/train.py", line 134, in main
cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
File "/home/gautam8/CDeCNet/mmdet/models/builder.py", line 48, in build_detector
return build(cfg, DETECTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
File "/home/gautam8/CDeCNet/mmdet/models/builder.py", line 20, in build
return build_from_cfg(cfg, registry, default_args)
File "/home/gautam8/.local/lib/python3.6/site-packages/mmcv/utils/registry.py", line 168, in build_from_cfg
return obj_cls(**args)
File "/home/gautam8/CDeCNet/mmdet/models/detectors/cascade_rcnn.py", line 23, in __init__
pretrained=pretrained)
File "/home/gautam8/CDeCNet/mmdet/models/detectors/two_stage.py", line 49, in __init__
self.init_weights(pretrained=pretrained)
File "/home/gautam8/CDeCNet/mmdet/models/detectors/two_stage.py", line 61, in init_weights
self.backbone.init_weights(pretrained=pretrained)
File "/home/gautam8/CDeCNet/mmdet/models/backbones/db_resnet.py", line 637, in init_weights
load_checkpoint(self, pretrained, strict=False, logger=logger)
File "/home/gautam8/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 211, in load_checkpoint
checkpoint = _load_checkpoint(filename, map_location)
File "/home/gautam8/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 183, in _load_checkpoint
checkpoint = load_url_dist(open_mmlab_model_urls[model_name])
File "/home/gautam8/.local/lib/python3.6/site-packages/mmcv/runner/checkpoint.py", line 139, in load_url_dist
checkpoint = model_zoo.load_url(url)
File "/home/gautam8/.local/lib/python3.6/site-packages/torch/hub.py", line 506, in load_state_dict_from_url
return torch.load(cached_file, map_location=map_location)
File "/home/gautam8/.local/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/home/gautam8/.local/lib/python3.6/site-packages/torch/serialization.py", line 709, in _legacy_load
deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
**RuntimeError: unexpected EOF, expected 59 more bytes. The file might be corrupted.**

**Comment by madhav1ag** [comment]
can you try with the latest checkpoints?
